export const resList = [
  {
    resName: "KFC",
    cuisine: "Burgers, Fast Food",
    star: "4.6",
    time: "20",
    image: "https://images.pexels.com/photos/1639562/pexels-photo-1639562.jpeg",
  },
  {
    resName: "McDonald's",
    cuisine: "Burgers, Beverages",
    star: "4.4",
    time: "18",
    image: "https://images.pexels.com/photos/3020919/pexels-photo-3020919.jpeg",
  },
  {
    resName: "Domino's Pizza",
    cuisine: "Pizza, Fast Food",
    star: "4.2",
    time: "25",
    image: "https://images.pexels.com/photos/1566837/pexels-photo-1566837.jpeg",
  },
  {
    resName: "Subway",
    cuisine: "Healthy Food, Sandwiches",
    star: "4.3",
    time: "22",
    image: "https://images.pexels.com/photos/1647163/pexels-photo-1647163.jpeg",
  },
  {
    resName: "Burger King",
    cuisine: "Burgers, Beverages",
    star: "4.1",
    time: "19",
    image: "https://images.pexels.com/photos/1556698/pexels-photo-1556698.jpeg",
  },
  {
    resName: "Pizza Hut",
    cuisine: "Pizza, Fast Food",
    star: "4.0",
    time: "24",
    image: "https://images.pexels.com/photos/367915/pexels-photo-367915.jpeg",
  },
  {
    resName: "Starbucks",
    cuisine: "Coffee, Beverages",
    star: "4.7",
    time: "15",
    image: "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg",
  },
  {
    resName: "Taco Bell",
    cuisine: "Mexican, Fast Food",
    star: "4.2",
    time: "23",
    image: "https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg",
  },
  {
    resName: "Haldiram's",
    cuisine: "Indian, Sweets",
    star: "4.5",
    time: "20",
    image: "https://images.pexels.com/photos/18488304/pexels-photo-18488304.jpeg",
  },
  {
    resName: "Bikanervala",
    cuisine: "North Indian, Mithai",
    star: "4.3",
    time: "21",
    image: "https://images.pexels.com/photos/8887055/pexels-photo-8887055.jpeg",
  },
  {
    resName: "Cafe Coffee Day",
    cuisine: "Coffee, Snacks",
    star: "4.0",
    time: "17",
    image: "https://images.pexels.com/photos/2067396/pexels-photo-2067396.jpeg",
  },
  {
    resName: "Barbeque Nation",
    cuisine: "BBQ, North Indian",
    star: "4.6",
    time: "30",
    image: "https://images.pexels.com/photos/53148/shish-kebab-meat-skewer-vegetable-skewer-meat-products-53148.jpeg",
  },
  {
    resName: "Wow! Momo",
    cuisine: "Momos, Fast Food",
    star: "4.2",
    time: "16",
    image: "https://images.pexels.com/photos/33670191/pexels-photo-33670191.jpeg",
  },
  {
    resName: "Faasos",
    cuisine: "Rolls, North Indian",
    star: "4.4",
    time: "22",
    image: "https://images.pexels.com/photos/33709307/pexels-photo-33709307.jpeg",
  },
  {
    resName: "Behrouz Biryani",
    cuisine: "Biryani, Mughlai",
    star: "4.6",
    time: "28",
    image: "https://images.pexels.com/photos/4910320/pexels-photo-4910320.jpeg",
  },
  {
    resName: "FreshMenu",
    cuisine: "Healthy Food, Salads",
    star: "4.1",
    time: "18",
    image: "https://images.pexels.com/photos/257816/pexels-photo-257816.jpeg",
  },
  {
    resName: "Chai Point",
    cuisine: "Tea, Snacks",
    star: "4.3",
    time: "14",
    image: "https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg",
  },
  {
    resName: "The Belgian Waffle Co.",
    cuisine: "Desserts, Waffles",
    star: "4.7",
    time: "19",
    image: "https://media.istockphoto.com/id/1382005630/photo/chocolate-waffle.jpg?b=1&s=612x612&w=0&k=20&c=dLbcyJONf7ZenmKbFmVbA_UNmTh0nXunJpDhJjTEvEs=",
  },
  {
    resName: "Chinese Wok",
    cuisine: "Chinese, Asian",
    star: "4.2",
    time: "26",
    image: "https://images.pexels.com/photos/2347311/pexels-photo-2347311.jpeg",
  },
  {
    resName: "Giani's",
    cuisine: "Ice Cream, Desserts",
    star: "4.5",
    time: "12",
    image: "https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg",
  },
];

export const offersList = [
  {
    name: "KFC",
    category: "Restaurant",
    offer: "20%",
    image: "https://images.pexels.com/photos/1639562/pexels-photo-1639562.jpeg",
  },
  {
    name: "Starbucks",
    category: "Cafe",
    offer: "15%",
    image: "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg",
  },
  {
    name: "Domino's Pizza",
    category: "Restaurant",
    offer: "25%",
    image: "https://images.pexels.com/photos/1566837/pexels-photo-1566837.jpeg",
  },
  {
    name: "Cafe Coffee Day",
    category: "Cafe",
    offer: "20%",
    image: "https://images.pexels.com/photos/2067396/pexels-photo-2067396.jpeg",
  },
  {
    name: "Giani's",
    category: "Cafe",
    offer: "12%",
    image: "https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg",
  },
];

export const popularCategories = [
  {
    image: "https://images.pexels.com/photos/551991/pexels-photo-551991.jpeg",
    category: "Burgers and Fast Food",
    number: "4",
  }
];